# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jyothis Benny
title: Backend Developer
email: jyothisbenny75@gmail.com
# email_title: Email (Email title override)
phone: +91 8606390091
# phone_title: Phone (Phone title override)
website_title: Jyothis Benny

# Dark Mode (true/false/never)
darkmode: false

# Social links

github_username:  jyothisbenny
# stackoverflow_username: "00000001"
linkedin_username: jyothis-benny

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
# about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Software engineer with 3.4 years of experience in backend development and DevOps. 
  Passionate about solving challenging problems and eager to work on impactful projects..

  For the past year, I have been focused on building intelligent, scalable chatbots that can
  be trained on custom data and integrated with leading LLM engines like OpenAI, Claude, Hugging Face,
  and Llama. Leveraging frameworks like FastAPI and Flask, along with robust databases such as MySQL
  and Redis, I have developed highly scalable and high-performance systems.

  Throughout my career, I have successfully led multiple projects from the ground up,
  utilizing AWS services (S3, SES, EC2, IAM), Docker, Nginx, uWSGI, and qb. My expertise extends
  to IoT solutions and ERP systems, where I’ve gained a strong understanding of these essential
  business tools. Additionally, I have intermediate proficiency in React with Ant Design, completing
  two projects in this space.

  As a freelancer, I have worked on diverse projects, blending technical expertise with creativity
  to deliver tailored solutions. I am passionate about solving complex problems, staying updated
  with industry trends, and delivering high-quality, maintainable solutions that drive results.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
      - title: Private Data Chatbots
        description: |
          **Private Data Chatbots** — 2024 - Ongoing  
          Developing a full chatbot lifecycle: build, test, and deploy Gen AI chatbots securely and
          efficiently with your own data.

      - title: Automating CA Practices
        link: https://demo.caclouddesk.com/
        link_text: Try it here.
        additional_links:
            - title:  Try it here.
              icon: fab fa-google
              url: https://demo.caclouddesk.com/
        description: |
          **Automating CA Practices** — Nov 2022 - 2024  
          Led backend development on a software suite for Chartered Accountants. The solution
          automates legal and accounting tasks through features like document management, automated
          workflows, and a collaborative platform. It streamlines CA practice management and
          fosters a connected community.

      - title: ERP System For A Construction-Based Company
        description: |
          **ERP System For A Construction-Based Company** — 2021 - 2024  
          As a core member and backend lead, I developed integrated modules for Payroll, Project
          Management, Vendor Management, Travel Management, and Inventory Management during the
          implementation of the ERP system. My work on the backend infrastructure and team 
          collaboration significantly boosted the company’s productivity.

      - title: BidCliq Ad Management System
        description: |
          **BidCliq: Ad Management System** — Sep 2023 - 2024  
          Developed and managed the creation of "BidCliq," a revenue-management tool that integrates
          Google Ad Manager, Adsterra, and Bidder Settings to simplify website monetization. This tool
          helps website owners maximize ad revenue by integrating multiple ad managers and reaching
          a wider audience of bidders.

  #        title: Project name
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
#        additional_links:
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        quote: >
#          Short overview of the project (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Edgebricks Inc
        sub_title: Backend Developer
        caption: May 2024 - present
        link: https://edgebricks.com/
        description: | # this will include new lines to allow paragraphs
          Developed a secure, scalable platform for building, testing, and deploying chatbots using private data,
          ensuring full control and data privacy by operating entirely within the company’s infrastructure and firewall.
          
          Integrated multiple large language models (LLMs) to offer flexibility and improved chatbot performance,
          while eliminating the need for third-party SaaS solutions, allowing businesses to customize and manage
          their AI-driven interactions.
          
          Focused on compliance with security standards and seamless integration with enterprise systems,
          empowering businesses to deploy AI chatbots safely and efficiently while enhancing customer engagement.

#        quote: >
#          Building intelligent chatbots: Train on your data, choose your
#          engine (OpenAI, Claude, Voyage AI, Hugging Face, Llama).
      - layout: right
        title: Plutonic Services Pvt. Ltd.
        sub_title: Full Stack Developer
        caption: June 2022 - May 2024
        link: https://www.plutonic.co.in/
        description: | # this will include new lines to allow paragraphs
          Led backend development and DevOps: Designed, developed, and deployed APIs and microservices.
          
          Took charge of full-stack execution: Collected requirements, designed system architecture,
          and maintained code quality through reviews.
          
          Delivered scalable solutions: Built strong backend systems using Django REST, Celery,
          Redis, PostgreSQL, Swagger, and DevOps practices to ensure smooth and efficient operations.
      - layout: right
        title: Plutonic Services Pvt. Ltd.
        sub_title: Full Stack Developer - Intern
        caption: Aug 2021 - May 2022
        link: https://www.plutonic.co.in/
        description: | # this will include new lines to allow paragraphs
          Contributed to backend development: Designed, developed, and tested backend components for
          internal projects.
          
          Worked closely with senior developers to maintain code quality and meet deadlines.
          
          Supported full-stack development: Collected requirements, helped with system design,
          and implemented backend functionalities.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Marian College Kuttikkanam(Autonomous)
        sub_title: Master of Computer Applications(MCA)
        caption: 2020 - 2022
      - layout: top-right
        title: St. Joseph’s College Moolamattom
        sub_title: Bachelor of Computer Applications(BCA)
        caption: 2017 - 2020

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I’m someone who loves to learn new things and always gives my best effort. I work hard to get
      things done and try to finish my to-do list every day. While I can be a bit lazy sometimes,
      I do my best to make each day productive and keep moving forward.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
